//
// Created by 長井亨 on 2019-08-10.
//

#ifndef NAGATO_RENDER_SRC_INTEGRATOR_INTEGRATOR_HPP_
#define NAGATO_RENDER_SRC_INTEGRATOR_INTEGRATOR_HPP_

class Integrator {

};

#endif //NAGATO_RENDER_SRC_INTEGRATOR_INTEGRATOR_HPP_
